CREATE  schema Grocery_Store_db;
USE Grocery_Store_db;

CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);
desc supplier;
select * from grocery_store_db.supplier;

CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);
desc grocery_store_db.categories;
select * from grocery_store_db.categories;

CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255), 
    hire_date VARCHAR(255)
);
desc grocery_store_db.employees;
select * from grocery_store_db.employees;

CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);
desc grocery_store_db.customers;
select * from grocery_store_db.customers; 

CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
desc grocery_store_db.products;
select * from grocery_store_db.products;

CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
desc grocery_store_db.orders;
select * from grocery_store_db.orders;

CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
desc grocery_store_db.order_details;
select * from grocery_store_db.order_details;

-- 1)How many unique customers have placed orders?
SELECT
count(DISTINCT cust_id) as unique_customers 
from orders;

-- 2)Which customers have placed the highest number of orders?
select 
c.cust_id,c.cust_name,COUNT(o.ord_id) AS total_orders
from 
customers c
JOIN 
orders o ON c.cust_id=o.cust_id
GROUP BY c.cust_id
ORDER BY total_orders DESC
LIMIT 1;

-- 3)What is the total and average purchase value per customer?
SELECT 
	o.cust_id,
    c.cust_name,
	SUM(od.total_price) AS total_purchase,
	AVG(od.total_price) AS avg_purchase
FROM 
	orders o
		JOIN 
	order_details od ON o.ord_id=od.ord_id
		JOIN 
	customers c ON o.cust_id=c.cust_id
GROUP BY o.cust_id;

-- 4)Who are the top 5 customers by total purchase amount
SELECT 
	o.cust_id,
    c.cust_name,
	SUM(od.total_price) AS total_purchase
FROM
	orders o
		JOIN
	order_details od ON o.ord_id=od.ord_id
		JOIN
	customers c ON o.cust_id=c.cust_id
GROUP BY o.cust_id
ORDER BY total_purchase DESC
LIMIT 5;

-- 5)How many products exist in each category?
SELECT
	c.cat_id,cat_name,COUNT(p.prod_id) AS total_products
FROM
	categories c
		LEFT JOIN
        products p ON c.cat_id=p.cat_id
GROUP BY c.cat_id;

-- 6)What is the average price of products by category?
SELECT
	c.cat_id,c.cat_name, AVG(p.price) AS avg_price
FROM 
	categories c
		LEFT JOIN
	products p ON c.cat_id=p.cat_id
 GROUP BY c.cat_id;
 
-- 7)Which products have the highest total sales volume (by quantity)?
SELECT 
	p.prod_name, SUM(o.quantity) AS high_sales
FROM
	order_details o
		LEFT JOIN
	products p ON o.prod_id=p.prod_id
GROUP BY p.prod_name
ORDER BY  high_sales DESC
LIMIT 1;

-- 8)What is the total revenue generated by each product?
SELECT
	SUM(o.total_price) AS total_revenue,p.prod_name
FROM 
	order_details o
		LEFT JOIN
	products p ON o.prod_id=p.prod_id
GROUP BY prod_name;

-- 9)How do products sales vary by category and supplier?
SELECT
	c.cat_name,s.sup_name, SUM(o.total_price) AS total_sales
FROM 
	order_details o
		JOIN 
	products p ON o.prod_id=p.prod_id
		JOIN
	categories c ON p.cat_id=c.cat_id
		JOIN 
	supplier s ON p.sup_id=s.sup_id
GROUP BY c.cat_name, s.sup_name
ORDER BY c.cat_name, total_sales DESC;

-- 10)How many orders have been placed in total?
SELECT 
	COUNT(*) AS total_orders
FROM
	orders;

-- 11)What is the average value per order?
SELECT
	SUM(total_price) / COUNT(DISTINCT ord_id) AS avg_order_value
FROM 
	order_details;

-- 12)On which dates were the most orders placed?
SELECT
	order_date, COUNT(ord_id) AS orders_count
FROM
	orders
GROUP BY order_date
ORDER BY orders_count DESC
LIMIT 1;

-- 13)What are the monthly trends in order volume and revenue?
SELECT 
	LEFT(o.order_date,7) AS order_month,
	COUNT(DISTINCT o.ord_id) AS order_volume,
	SUM(od.total_price) AS total_revenue

FROM
	orders o
		JOIN 
	order_details od ON o.ord_id=od.ord_id
GROUP BY order_month
ORDER BY order_month;


-- 14)How do order patterns vary across weekdays and months?
UPDATE orders
SET order_date =DATE_FORMAT(STR_TO_DATE(order_date, '%m/%d/%Y'), '%Y-%m-%d');

SELECT
    DAYNAME(STR_TO_DATE(order_date, '%Y-%m-%d')) AS weekday,
    MONTHNAME(STR_TO_DATE(order_date, '%Y-%m-%d')) AS month,
    COUNT(ord_id) AS total_orders
FROM 
	orders
GROUP BY weekday, month
ORDER BY weekday, month;


-- 15)How many suppliers are there in the database?
SELECT 
	COUNT(*) 
FROM
	supplier;

-- 16)Which supplier provides the most products?
SELECT 
	s.sup_id,sup_name, COUNT(p.prod_id) AS product_count
FROM
	supplier s
		JOIN	
	products p ON s.sup_id=p.sup_id
GROUP BY s.sup_id
ORDER BY product_count DESC
LIMIT 1;

-- 17)What is the average price of products from each supplier?
SELECT 
	s.sup_id,s.sup_name, AVG(p.price)
FROM
	products p
		JOIN 
	supplier s ON s.sup_id=p.sup_id
GROUP BY s.sup_id;

-- 18)Which suppliers contribute the most to total product sales (by revenue)?
SELECT
	s.sup_id,s.sup_name, SUM(od.total_price) AS  total_revenue
FROM 
	supplier s
		JOIN 
	products p ON s.sup_id=p.sup_id
		JOIN
	order_details od ON p.prod_id=od.prod_id
GROUP BY s.sup_id
ORDER BY total_revenue DESC
LIMIT 1;

-- 19)How many employees have processed orders?
SELECT 
	COUNT(DISTINCT emp_id)
FROM
	orders;

-- 20)Which employees have handled the most orders?
SELECT 
	e.emp_id,e.emp_name, COUNT(o.ord_id) AS ordered_most
FROM 
	orders o
		JOIN
	employees e ON o.emp_id=e.emp_id
GROUP BY e.emp_id
ORDER BY ordered_most DESC
LIMIT 1;

-- 21)What is the total sales value processed by each employee?
SELECT
	e.emp_id,e.emp_name, SUM(od.total_price) AS total_sales
FROM 
	employees e
		JOIN 
	orders o ON o.emp_id=e.emp_id
		JOIN
	order_details od ON o.ord_id=od.ord_id
GROUP BY e.emp_id
ORDER BY total_sales DESC;

-- 22)What is the average order value handled per employee?
SELECT 
	e.emp_id,
    e.emp_name,
    SUM(od.total_price) / COUNT(DISTINCT o.ord_id) AS avg_value
FROM 
	employees e 
		JOIN
	orders o ON e.emp_id=o.emp_id
		JOIN
	order_details od ON o.ord_id=od.ord_id
GROUP BY e.emp_id
ORDER BY avg_value DESC;

-- 23)What is the relationship between quantity ordered and total price?
SELECT
	quantity,
	AVG(od.total_price) AS avg_total_price,
	COUNT(*) AS order_count
FROM order_details od
GROUP BY  quantity
ORDER BY quantity;

-- 24)What is the average quantity ordered per product?
SELECT
	p.prod_id,
	prod_name,
    COUNT(od.ord_id)  AS total_orders,
	AVG(od.quantity)  AS avg_quantity_ordered
FROM 
	products p
		JOIN
	order_details od ON p.prod_id=od.prod_id
GROUP BY p.prod_id
ORDER BY avg_quantity_ordered DESC;

-- 25)How does the unit price vary across products and orders?
SELECT
	p.prod_id,
    p.prod_name,
    od.each_price AS unit_price,
	COUNT(od.ord_id) AS times_ordered
FROM 
	products p
		JOIN
	order_details od ON p.prod_id=od.prod_id
GROUP BY p.prod_id,od.each_price
ORDER BY p.prod_id,od.each_price;